### ISSUE TITLE
npm install: Cannot find module

### ISSUE THREAD

**Issue by mickeyl** [benwaffle/vala-language-server#5]
I tried to follow your instructions, but `npm install` bails out for me with the following.
Apparently it is looking for a directory `vscode`, which is not existing. Is that a problem on my end?

```
npm install                                                                                                                                     mickey@helios

> vala@0.3.1 postinstall /usr/local/lib/node_modules/vala
> node ./node_modules/vscode/bin/install

module.js:557
    throw err;
    ^

Error: Cannot find module '/Users/mickey/Documents/late/misc/vala-code/node_modules/vscode/bin/install'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
npm WARN rollback Rolling back vscode-jsonrpc@3.5.0 failed (this is probably harmless): /Users/mickey/Documents/late/misc/vala-code/node_modules/vscode-jsonrpc is not a child of /usr/local/lib
npm WARN rollback Rolling back vscode-languageserver-types@3.5.0 failed (this is probably harmless): /Users/mickey/Documents/late/misc/vala-code/node_modules/vscode-languageserver-types is not a child of /usr/local/lib
npm WARN rollback Rolling back vscode-languageserver-protocol@3.5.0 failed (this is probably harmless): /Users/mickey/Documents/late/misc/vala-code/node_modules/vscode-languageserver-protocol is not a child of /usr/local/lib
npm WARN rollback Rolling back vscode-languageclient@3.5.0 failed (this is probably harmless): /Users/mickey/Documents/late/misc/vala-code/node_modules/vscode-languageclient is not a child of /usr/local/lib
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vala@0.3.1 postinstall: `node ./node_modules/vscode/bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vala@0.3.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mickey/.npm/_logs/2018-02-18T19_56_42_762Z-debug.log
```

**Comment by mickeyl** [comment]
I'm really trying to get this installed here, but falling from error to error. Would it be possible to provide a VSIX for that?

**Comment by mickeyl** [comment]
Ok, my fault. Years ago, I have aliased `npm` to `npm -g`, which is why it breaks for `npm install`. Without the `-g` it just works and I have created the `vsix` with `vsce`. Trying to install it now. Sorry for the noise.

**Comment by benwaffle** [comment]
aliasing npm to npm -g is not a great idea :)
